### ISSUE TITLE
Fetch new domains periodically

### ISSUE THREAD

**Issue by andreis** [andreis/disposable-email-domains#1]
* [x] improve python script
* [x] make it run automatically using travis-ci

**Comment by smeinecke** [comment]
Could you add me to this repository too? I'd like to automate this and link the main repository as submodule :)

**Comment by andreis** [comment]
Access granted.

I'm literally 24/7 busy with my job so I can't help, sorry about that. But I really do appreciate your input – can you add a link to yourself in the `README`s to get credit for your work? Thanks!
