### ISSUE TITLE
Is com.ar, Argentina's TLD, intended to be on this list?

### ISSUE THREAD

**Issue by Taytay** [andreis/disposable-email-domains#10]
`com.ar` is the TLD for Argentina, and is currently on the list: 
https://github.com/andreis/disposable-email-domains/blob/master/domains.txt#L4195

Perhaps incorrectly, we are using this list as a list of domains, and thus also block any subdomains of those listed here. That means that we are currently blocking live.com.ar. It's obviously trivial for us to stop interpreting `com.ar` that way, but I wanted to raise it as an issue in case `com.ar`'s presence in the list was a mistake.

**Comment by smeinecke** [comment]
Sorry for this issue. Should be fixed in next update!
