### ISSUE TITLE
Luxus

### ISSUE THREAD

**Issue by nunoperalta** [andreis/disposable-email-domains#11]
More to add: https://www.luxusmail.org/

@luxusmail.gq
@bitchmail.ga
@bitchmail.ga
@onedaymail.ga
@linuxmail.tk
@10minute.cf
@onedaymail.cf
@luxusmail.tk
@luxusmail.uk

**Comment by smeinecke** [comment]
Domains still active?

**Comment by smeinecke** [comment]
Thank you for the info 👍 Will add a crawler for this - service was down last time I checked - is back online now.
