### ISSUE TITLE
New domains

### ISSUE THREAD

**Issue by luecano** [andreis/disposable-email-domains#15]
Please add domains from temp-mail.org: 

mailhub24.com
iwebtm.com
3mailapp.net
hide-mail.net
net3mail.com
itymail.com
hideemail.net
resmail24.com
inwebtm.com
ymail365.com

**Comment by smeinecke** [comment]
fixed in latest release.

**Comment by luecano** [comment]
New temp-mail.org domains:

imailt.com
topmail2.net
mailapp.top
mailt.net
mail-now.top
topmail2.com
mailt.top
promailt.com
one-mail.top
newmail.top

**Comment by smeinecke** [comment]
Thank you for message, but the domains are already in the latest commit 274d3fa76834fb83f6860dfb70ab0e662248b6a6. The files are updated every 24 hours by the script in repo https://github.com/andreis/disposable which fetch the domains listed on temp-mail.org :)
