### ISSUE TITLE
gmail.com on the list

### ISSUE THREAD

**Issue by sun2rise** [andreis/disposable-email-domains#2]
Hi,
I noticed that in [the last commit](https://github.com/andreis/disposable-email-domains/commit/3743906114ffee06140ca5bbbe7d6ada19ce9af7) you added **gmail.com**.

But I think it should not blacklisted.. is there a reason?

**Comment by smeinecke** [comment]
Thanks for that advice. The update process is fully automated and that is for sure a big mistake. I'll update asap.
