### ISSUE TITLE
New domain

### ISSUE THREAD

**Issue by hotgeart** [andreis/disposable-email-domains#5]
https://mail.bhadoomail.com/inbox/?nyscieda79@dotmail.gq (click on change email to get this list)

- bhadoomail.com
- dotmail.gq
- dotmail.cf
- dotmail.ga
- hashhackers.com.test-google-a.com

Other domains spam user used on my website but I don't know the source:

- jo-mail.com
- plutocow.com
- mail-2-you.com
- reddcoin2.com
- prmail.top
- 2mailnext.com
- youmails.online

**Comment by smeinecke** [comment]
Service on bhadoomail.com not active anymore. Other domains in list. Thanks for you help 👍
