### ISSUE TITLE
Blur's alternative domains

### ISSUE THREAD

**Issue by martin-braun** [andreis/disposable-email-domains#6]
Abine Blur doesn't just offer creations of disposable opayq.com emails, they also allow to create emails using those domains: 

moremobileprivacy.com
blurme.net
icogneato.co
ipriva.net

Please add those, thanks.

**Comment by smeinecke** [comment]
Service still active?

**Comment by l-Marty-l** [comment]
> Service still active?

yes -> https://abine.com

their email choices have no been changed in the meantime:
![image](https://user-images.githubusercontent.com/24259245/70148138-e411ad00-16a5-11ea-8795-802eb4a70fd4.png)

**Comment by smeinecke** [comment]
Thanks for the info 👍 will try to add some parser for that site.
